#!/usr/bin/perl
# -*- perl -*-

# Copyright (c) 2002-2005 Intel Corporation
# All rights reserved.
#
# This file is distributed under the terms in the attached INTEL-LICENSE     
# file. If you do not find these files, copies can be found by writing to
# Intel Research Berkeley, 2150 Shattuck Avenue, Suite 1300, Berkeley, CA, 
# 94704.  Attention:  Intel License Inquiry.

$prefix = "/usr/local";
$exec_prefix = "${prefix}";

if ($#ARGV < 1) {
    &fail("Usage: nesdoc <documentation directory> <options and nesC files>");
}

$docdir = shift @ARGV;

unshift @ARGV, "-docdir=$docdir";
unshift @ARGV, "-fsyntax-only";
unshift @ARGV, "$exec_prefix/bin/ncc";

exec @ARGV;
print STDERR "Couldn't execute $exec_prefix/bin/ncc\n";
exit 2;

sub fail {
    print STDERR "$_[0]\n";
    exit 2;
}

