BASE_DIR = $(TOSROOT)/apps/tests/TestRadioPM/apps

COMPONENT=ChainedForwarderAppC

CFLAGS += -I$(BASE_DIR)/../apps/TestSleepSchedulers
include $(BASE_DIR)/TestSleepSchedulers/MakeIncludes

include $(MAKERULES)

