COMPONENT=BlinkAppC
CFLAGS += -I%T/lib/oski 
#-I%T/chips/atm128/sim -I%T/chips/atm128 -I%T/chips/atm128/timer/sim -I%T/chips/atm128/timer -I%T/platforms/mica/sim -I%T/platforms/mica -I%T/chips/atm128/pins/sim -I%T/chips/atm128/pins -I%T/chips/atm128/adc/sim -I%T/chips/atm128/adc -I%T/lib/timer

include $(MAKERULES)

