/**
 * This class is automatically generated by mig. DO NOT EDIT THIS FILE.
 * This class implements a Java interface to the 'NumSenderMsgs'
 * message type.
 */

public class NumSenderMsgs extends net.tinyos.message.Message {

    /** The default size of this message type in bytes. */
    public static final int DEFAULT_MESSAGE_SIZE = 60;

    /** The Active Message type associated with this message. */
    public static final int AM_TYPE = 241;

    /** Create a new NumSenderMsgs of size 60. */
    public NumSenderMsgs() {
        super(DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /** Create a new NumSenderMsgs of the given data_length. */
    public NumSenderMsgs(int data_length) {
        super(data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new NumSenderMsgs with the given data_length
     * and base offset.
     */
    public NumSenderMsgs(int data_length, int base_offset) {
        super(data_length, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new NumSenderMsgs using the given byte array
     * as backing store.
     */
    public NumSenderMsgs(byte[] data) {
        super(data);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new NumSenderMsgs using the given byte array
     * as backing store, with the given base offset.
     */
    public NumSenderMsgs(byte[] data, int base_offset) {
        super(data, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new NumSenderMsgs using the given byte array
     * as backing store, with the given base offset and data length.
     */
    public NumSenderMsgs(byte[] data, int base_offset, int data_length) {
        super(data, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new NumSenderMsgs embedded in the given message
     * at the given base offset.
     */
    public NumSenderMsgs(net.tinyos.message.Message msg, int base_offset) {
        super(msg, base_offset, DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new NumSenderMsgs embedded in the given message
     * at the given base offset and length.
     */
    public NumSenderMsgs(net.tinyos.message.Message msg, int base_offset, int data_length) {
        super(msg, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
    /* Return a String representation of this message. Includes the
     * message type name and the non-indexed field values.
     */
    public String toString() {
      String s = "Message <NumSenderMsgs> \n";
      try {
        s += "  [numMsgs=";
        for (int i = 0; i < 15; i++) {
          s += "0x"+Long.toHexString(getElement_numMsgs(i) & 0xff)+" ";
        }
        s += "]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      return s;
    }

    // Message-type-specific access methods appear below.

    /////////////////////////////////////////////////////////
    // Accessor methods for field: numMsgs
    //   Field type: long[], unsigned
    //   Offset (bits): 0
    //   Size of each element (bits): 32
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'numMsgs' is signed (false).
     */
    public static boolean isSigned_numMsgs() {
        return false;
    }

    /**
     * Return whether the field 'numMsgs' is an array (true).
     */
    public static boolean isArray_numMsgs() {
        return true;
    }

    /**
     * Return the offset (in bytes) of the field 'numMsgs'
     */
    public static int offset_numMsgs(int index1) {
        int offset = 0;
        if (index1 < 0 || index1 >= 15) throw new ArrayIndexOutOfBoundsException();
        offset += 0 + index1 * 32;
        return (offset / 8);
    }

    /**
     * Return the offset (in bits) of the field 'numMsgs'
     */
    public static int offsetBits_numMsgs(int index1) {
        int offset = 0;
        if (index1 < 0 || index1 >= 15) throw new ArrayIndexOutOfBoundsException();
        offset += 0 + index1 * 32;
        return offset;
    }

    /**
     * Return the entire array 'numMsgs' as a long[]
     */
    public long[] get_numMsgs() {
        long[] tmp = new long[15];
        for (int index0 = 0; index0 < numElements_numMsgs(0); index0++) {
            tmp[index0] = getElement_numMsgs(index0);
        }
        return tmp;
    }

    /**
     * Set the contents of the array 'numMsgs' from the given long[]
     */
    public void set_numMsgs(long[] value) {
        for (int index0 = 0; index0 < value.length; index0++) {
            setElement_numMsgs(index0, value[index0]);
        }
    }

    /**
     * Return an element (as a long) of the array 'numMsgs'
     */
    public long getElement_numMsgs(int index1) {
        return (long)getUIntBEElement(offsetBits_numMsgs(index1), 32);
    }

    /**
     * Set an element of the array 'numMsgs'
     */
    public void setElement_numMsgs(int index1, long value) {
        setUIntBEElement(offsetBits_numMsgs(index1), 32, value);
    }

    /**
     * Return the total size, in bytes, of the array 'numMsgs'
     */
    public static int totalSize_numMsgs() {
        return (480 / 8);
    }

    /**
     * Return the total size, in bits, of the array 'numMsgs'
     */
    public static int totalSizeBits_numMsgs() {
        return 480;
    }

    /**
     * Return the size, in bytes, of each element of the array 'numMsgs'
     */
    public static int elementSize_numMsgs() {
        return (32 / 8);
    }

    /**
     * Return the size, in bits, of each element of the array 'numMsgs'
     */
    public static int elementSizeBits_numMsgs() {
        return 32;
    }

    /**
     * Return the number of dimensions in the array 'numMsgs'
     */
    public static int numDimensions_numMsgs() {
        return 1;
    }

    /**
     * Return the number of elements in the array 'numMsgs'
     */
    public static int numElements_numMsgs() {
        return 15;
    }

    /**
     * Return the number of elements in the array 'numMsgs'
     * for the given dimension.
     */
    public static int numElements_numMsgs(int dimension) {
      int array_dims[] = { 15,  };
        if (dimension < 0 || dimension >= 1) throw new ArrayIndexOutOfBoundsException();
        if (array_dims[dimension] == 0) throw new IllegalArgumentException("Array dimension "+dimension+" has unknown size");
        return array_dims[dimension];
    }

}
