#!/bin/sh

set -e

srcdir=src

ACLOCAL="aclocal"
AUTOMAKE="automake"
AUTOCONF="autoconf"
AUTOHEADER="autoheader"

set -x
(
    $ACLOCAL
    $AUTOCONF
    [ -d config-aux ] || mkdir config-aux
    $AUTOMAKE -a -c

    (cd platforms/mica/uisp; ./bootstrap)
)
rm -f config.cache $srcdir/config.cache
